
language: cpp
sudo: required
dist: trusty

matrix:
  include:

  - os: linux
    compiler: gcc
    env: COMPILER=g++-4.9
    addons:
      apt:
        sources: 
          - ubuntu-toolchain-r-test
        packages:
          - g++-4.9

  - os: linux
    compiler: clang

  - os: osx
    osx_image: xcode9

script:

  - cmake -DCMAKE_CXX_COMPILER=$COMPILER . && make
