
language: cpp
sudo: required
dist: bionic

matrix:
  include:

  - os: linux
    compiler: gcc

  - os: linux
    compiler: clang

  - os: osx
    compiler: clang
    osx_image: xcode11.3


script:

  - cmake -DCMAKE_CXX_COMPILER=$COMPILER . && make
