
language: cpp
sudo: required

matrix:
  include:

  - os: linux
    compiler: gcc
    env: COMPILER=g++-4.9
    addons:
      apt:
        sources: ['ubuntu-toolchain-r-test']
        packages: ['g++-4.9']

  - os: linux
    compiler: clang

script:
  - cmake .
  - make
